Define a function named basic_clean. It should take in a string and apply some basic text cleaning to it:

Lowercase everything
Normalize unicode characters
Replace anything that is not a letter, number, whitespace or a single quote.
Define a function named tokenize. It should take in a string and tokenize all the words in the string.

Define a function named stem. It should accept some text and return the text after applying stemming to all the words.

Define a function named lemmatize. It should accept some text and return the text after applying lemmatization to each word.

Define a function named remove_stopwords. It should accept some text and return the text after removing all the stopwords.

This function should define two optional parameters, extra_words and exclude_words. These parameters should define any additional stop words to include, and any words that we don't want to remove.

Use your data from the acquire to produce a dataframe of the news articles. Name the dataframe news_df.

Make another dataframe for the Codeup blog posts. Name the dataframe codeup_df.

For each dataframe, produce the following columns:

title to hold the title
original to hold the original article/post content
clean to hold the normalized and tokenized original with the stopwords removed.
stemmed to hold the stemmed version of the cleaned data.
lemmatized to hold the lemmatized version of the cleaned data.
Ask yourself:

If your corpus is 493KB, would you prefer to use stemmed or lemmatized text?
If your corpus is 25MB, would you prefer to use stemmed or lemmatized text?
If your corpus is 200TB of text and you're charged by the megabyte for your hosted computational resources, would you prefer to use stemmed or lemmatized text?

In [1]:
import unicodedata
import re
import json

import nltk
from nltk.tokenize.toktok import ToktokTokenizer
from nltk.corpus import stopwords

import pandas as pd
import acquire as a


#import
import warnings
warnings.filterwarnings("ignore")

In [5]:
#From the class exercise
df = a.get_blog_articles(use_cache=True)

In [6]:
df

,title,published,content
0,Learn to Code: Python Workshop on 4/23,"Mar 31, 2022","According to LinkedIn, the “#1 Most Promising ..."
1,Coming Soon: Cloud Administration,"Mar 17, 2022",We’re launching a new program out of San Anton...
2,5 Books Every Woman In Tech Should Read,"Mar 8, 2022",On this International Women’s Day 2022 we want...
3,Codeup Start Dates for March 2022,"Jan 26, 2022",As we approach the end of January we wanted to...
4,VET TEC Funding Now Available For Dallas Veterans,"Jan 7, 2022",We are so happy to announce that VET TEC benef...
5,Dallas Campus Re-opens With New Grant Partner,"Dec 30, 2021",We are happy to announce that our Dallas campu...
6,Codeup’s Placement Team Continues Setting Records,"Nov 19, 2021",Our Placement Team is simply defined as a grou...
7,"IT Certifications 101: Why They Matter, and Wh...","Nov 18, 2021","AWS, Google, Azure, Red Hat, CompTIA…these are..."
8,A rise in cyber attacks means opportunities fo...,"Nov 17, 2021","In the last few months, the US has experienced..."
9,Use your GI Bill® benefits to Land a Job in Tech,"Nov 4, 2021","As the end of military service gets closer, ma..."
10,Which program is right for me: Cyber Security ...,"Oct 28, 2021",What IT Career should I choose?\nIf you’re thi...
11,What the Heck is System Engineering?,"Oct 21, 2021",Codeup offers a 13-week training program: Syst...
12,From Speech Pathology to Business Intelligence,"Oct 18, 2021","By: Alicia Gonzalez\nBefore Codeup, I was a ho..."
13,Boris – Behind the Billboards,"Oct 3, 2021",
14,Is Codeup the Best Bootcamp in San Antonio…or ...,"Sep 16, 2021",Looking for the best data science bootcamp in ...

In [7]:
#solve for one column
df.title.str.lower()

0                learn to code: python workshop on 4/23
1                     coming soon: cloud administration
2               5 books every woman in tech should read
3                     codeup start dates for march 2022
4     vet tec funding now available for dallas veterans
5         dallas campus re-opens with new grant partner
6     codeup’s placement team continues setting records
7     it certifications 101: why they matter, and wh...
8     a rise in cyber attacks means opportunities fo...
9      use your gi bill® benefits to land a job in tech
10    which program is right for me: cyber security ...
11                 what the heck is system engineering?
12       from speech pathology to business intelligence
13                        boris – behind the billboards
14    is codeup the best bootcamp in san antonio…or ...
Name: title, dtype: object

In [8]:
#get each colum
df2=pd.DataFrame()
for column in df.columns:
    df2[column]= df[column].str.lower()

In [9]:
l =[df2.title[n] for n in range (0, len(df2))]

In [10]:
l

['learn to code: python workshop on 4/23',
 'coming soon: cloud administration',
 '5 books every woman in tech should read',
 'codeup start dates for march 2022',
 'vet tec funding now available for dallas veterans',
 'dallas campus re-opens with new grant partner',
 'codeup’s placement team continues setting records',
 'it certifications 101: why they matter, and why they don’t',
 'a rise in cyber attacks means opportunities for veterans in san antonio',
 'use your gi bill® benefits to land a job in tech',
 'which program is right for me: cyber security or systems engineering?',
 'what the heck is system engineering?',
 'from speech pathology to business intelligence',
 'boris – behind the billboards',
 'is codeup the best bootcamp in san antonio…or the world?']

In [11]:
for column in df2.columns:
    l =[unicodedata.normalize('NFKC',df2[column][n]) for n in range (0, len(df2))]
    df2[column]= l

In [12]:
df2

,title,published,content
0,learn to code: python workshop on 4/23,"mar 31, 2022","according to linkedin, the “#1 most promising ..."
1,coming soon: cloud administration,"mar 17, 2022",we’re launching a new program out of san anton...
2,5 books every woman in tech should read,"mar 8, 2022",on this international women’s day 2022 we want...
3,codeup start dates for march 2022,"jan 26, 2022",as we approach the end of january we wanted to...
4,vet tec funding now available for dallas veterans,"jan 7, 2022",we are so happy to announce that vet tec benef...
5,dallas campus re-opens with new grant partner,"dec 30, 2021",we are happy to announce that our dallas campu...
6,codeup’s placement team continues setting records,"nov 19, 2021",our placement team is simply defined as a grou...
7,"it certifications 101: why they matter, and wh...","nov 18, 2021","aws, google, azure, red hat, comptia...these a..."
8,a rise in cyber attacks means opportunities fo...,"nov 17, 2021","in the last few months, the us has experienced..."
9,use your gi bill® benefits to land a job in tech,"nov 4, 2021","as the end of military service gets closer, ma..."
10,which program is right for me: cyber security ...,"oct 28, 2021",what it career should i choose?\nif you’re thi...
11,what the heck is system engineering?,"oct 21, 2021",codeup offers a 13-week training program: syst...
12,from speech pathology to business intelligence,"oct 18, 2021","by: alicia gonzalez\nbefore codeup, i was a ho..."
13,boris – behind the billboards,"oct 3, 2021",
14,is codeup the best bootcamp in san antonio...o...,"sep 16, 2021",looking for the best data science bootcamp in ...

In [13]:
#we need to do it by stringso we can use a comprehension list to do the rows
for column in df2.columns:
    df2[column]= [re.sub(r"[^a-z0-9'\s]", '', df2[column][n] ) for n in range (0, len(df2))]

In [14]:
df2

,title,published,content
0,learn to code python workshop on 423,mar 31 2022,according to linkedin the 1 most promising job...
1,coming soon cloud administration,mar 17 2022,were launching a new program out of san antoni...
2,5 books every woman in tech should read,mar 8 2022,on this international womens day 2022 we wante...
3,codeup start dates for march 2022,jan 26 2022,as we approach the end of january we wanted to...
4,vet tec funding now available for dallas veterans,jan 7 2022,we are so happy to announce that vet tec benef...
5,dallas campus reopens with new grant partner,dec 30 2021,we are happy to announce that our dallas campu...
6,codeups placement team continues setting records,nov 19 2021,our placement team is simply defined as a grou...
7,it certifications 101 why they matter and why ...,nov 18 2021,aws google azure red hat comptiathese are big ...
8,a rise in cyber attacks means opportunities fo...,nov 17 2021,in the last few months the us has experienced ...
9,use your gi bill benefits to land a job in tech,nov 4 2021,as the end of military service gets closer man...
10,which program is right for me cyber security o...,oct 28 2021,what it career should i choose\nif youre think...
11,what the heck is system engineering,oct 21 2021,codeup offers a 13week training program system...
12,from speech pathology to business intelligence,oct 18 2021,by alicia gonzalez\nbefore codeup i was a home...
13,boris behind the billboards,oct 3 2021,
14,is codeup the best bootcamp in san antonioor t...,sep 16 2021,looking for the best data science bootcamp in ...

In [15]:
# create a function
def clean_df(df):
    '''
    takes in a df and lowercase everything, normalize unicode characters, replace anything that is not a letter,
    number, whitespace or a single quote.
    retunr a clean df
    '''
    for column in df.columns:
        #get lowercase
        df[column]= df[column].str.lower()
        #normalize
        df[column]= [unicodedata.normalize('NFKC',df[column][n])\
                     .encode('ascii', 'ignore')\
                    .decode('utf-8') for n in range (0, len(df))]
        #remove special characters
        df[column]= [re.sub(r"[^a-z0-9'\s]", '', df[column][n] ) for n in range (0, len(df))]
    return df

In [16]:
def basic_clean (string):
    '''
    takes in a string and lowercase everything, normalize unicode characters, replace anything that is not a letter,
    number, whitespace or a single quote.
    retunr a clean string
    '''
    
    string = string.lower()
    string = unicodedata.normalize('NFKC',string)\
    .encode('ascii', 'ignore')\
    .decode('utf-8')
    string = re.sub(r"[^a-z0-9'\s]", '', string)
    return string

In [20]:
def basic_clean_df (df):
    '''
    takes in a df and using the function basic_clean lowercase everything, normalize unicode characters, replace anything that is not a letter,
    number, whitespace or a single quote.
    retunr a clean df
    '''
    for column in df.columns:
        df[column]= [basic_clean(df[column][string]) for string in range(0, len(df))]
    return df

In [17]:
basic_clean(df.content[0])

'according to linkedin the 1 most promising job is data science but we here at codeup understand changing careers can be a daunting idea thats where our free learn to code workshops come in \non saturday 423 we will be teaching a free learn to code workshop on the programming language python which is one of the major building blocks of data science\nwhat is data science what is python \nif youre curious join for free to learn the basics of python from our very own instructors and get an introduction to the field of data science this is all done from the comfort of home\nsave your seat quickly  our python workshops are always in high demand \nwhat you need\n1 laptop does not matter what kind you need to be able to access wifi and run an internet browser\n2 to rsvp\nyou can register for the event below'

In [18]:
#From the class exercise
df = a.get_blog_articles(use_cache=True)

In [21]:
df2 = basic_clean_df(df)

In [24]:
df2

,title,published,content
0,learn to code python workshop on 423,mar 31 2022,according to linkedin the 1 most promising job...
1,coming soon cloud administration,mar 17 2022,were launching a new program out of san antoni...
2,5 books every woman in tech should read,mar 8 2022,on this international womens day 2022 we wante...
3,codeup start dates for march 2022,jan 26 2022,as we approach the end of january we wanted to...
4,vet tec funding now available for dallas veterans,jan 7 2022,we are so happy to announce that vet tec benef...
5,dallas campus reopens with new grant partner,dec 30 2021,we are happy to announce that our dallas campu...
6,codeups placement team continues setting records,nov 19 2021,our placement team is simply defined as a grou...
7,it certifications 101 why they matter and why ...,nov 18 2021,aws google azure red hat comptiathese are big ...
8,a rise in cyber attacks means opportunities fo...,nov 17 2021,in the last few months the us has experienced ...
9,use your gi bill benefits to land a job in tech,nov 4 2021,as the end of military service gets closer man...
10,which program is right for me cyber security o...,oct 28 2021,what it career should i choose\nif youre think...
11,what the heck is system engineering,oct 21 2021,codeup offers a 13week training program system...
12,from speech pathology to business intelligence,oct 18 2021,by alicia gonzalez\nbefore codeup i was a home...
13,boris behind the billboards,oct 3 2021,
14,is codeup the best bootcamp in san antonioor t...,sep 16 2021,looking for the best data science bootcamp in ...

In [22]:
df3 = clean_df(df)

In [23]:
df3

,title,published,content
0,learn to code python workshop on 423,mar 31 2022,according to linkedin the 1 most promising job...
1,coming soon cloud administration,mar 17 2022,were launching a new program out of san antoni...
2,5 books every woman in tech should read,mar 8 2022,on this international womens day 2022 we wante...
3,codeup start dates for march 2022,jan 26 2022,as we approach the end of january we wanted to...
4,vet tec funding now available for dallas veterans,jan 7 2022,we are so happy to announce that vet tec benef...
5,dallas campus reopens with new grant partner,dec 30 2021,we are happy to announce that our dallas campu...
6,codeups placement team continues setting records,nov 19 2021,our placement team is simply defined as a grou...
7,it certifications 101 why they matter and why ...,nov 18 2021,aws google azure red hat comptiathese are big ...
8,a rise in cyber attacks means opportunities fo...,nov 17 2021,in the last few months the us has experienced ...
9,use your gi bill benefits to land a job in tech,nov 4 2021,as the end of military service gets closer man...
10,which program is right for me cyber security o...,oct 28 2021,what it career should i choose\nif youre think...
11,what the heck is system engineering,oct 21 2021,codeup offers a 13week training program system...
12,from speech pathology to business intelligence,oct 18 2021,by alicia gonzalez\nbefore codeup i was a home...
13,boris behind the billboards,oct 3 2021,
14,is codeup the best bootcamp in san antonioor t...,sep 16 2021,looking for the best data science bootcamp in ...

In [25]:
#get a string
string = df.content[0]

In [26]:
#clean the string
string = basic_clean(string)

In [27]:
string

'according to linkedin the 1 most promising job is data science but we here at codeup understand changing careers can be a daunting idea thats where our free learn to code workshops come in \non saturday 423 we will be teaching a free learn to code workshop on the programming language python which is one of the major building blocks of data science\nwhat is data science what is python \nif youre curious join for free to learn the basics of python from our very own instructors and get an introduction to the field of data science this is all done from the comfort of home\nsave your seat quickly  our python workshops are always in high demand \nwhat you need\n1 laptop does not matter what kind you need to be able to access wifi and run an internet browser\n2 to rsvp\nyou can register for the event below'

In [28]:
def tokenize (string):
    '''
    take in a string and tokenize all the words in the string
    '''
    
    # Create the tokenizer
    tokenizer = nltk.tokenize.ToktokTokenizer()
    # Use the tokenizer
    string = tokenizer.tokenize(string, return_str = True)
    return string

In [29]:
tokenize(string)

'according to linkedin the 1 most promising job is data science but we here at codeup understand changing careers can be a daunting idea thats where our free learn to code workshops come in \non saturday 423 we will be teaching a free learn to code workshop on the programming language python which is one of the major building blocks of data science\nwhat is data science what is python \nif youre curious join for free to learn the basics of python from our very own instructors and get an introduction to the field of data science this is all done from the comfort of home\nsave your seat quickly our python workshops are always in high demand \nwhat you need\n1 laptop does not matter what kind you need to be able to access wifi and run an internet browser\n2 to rsvp\nyou can register for the event below'

In [30]:
string

'according to linkedin the 1 most promising job is data science but we here at codeup understand changing careers can be a daunting idea thats where our free learn to code workshops come in \non saturday 423 we will be teaching a free learn to code workshop on the programming language python which is one of the major building blocks of data science\nwhat is data science what is python \nif youre curious join for free to learn the basics of python from our very own instructors and get an introduction to the field of data science this is all done from the comfort of home\nsave your seat quickly  our python workshops are always in high demand \nwhat you need\n1 laptop does not matter what kind you need to be able to access wifi and run an internet browser\n2 to rsvp\nyou can register for the event below'

In [31]:
# Create porter stemmer.
ps = nltk.porter.PorterStemmer()

# Apply the stemmer to each word in our string.
stems = [ps.stem(word) for word in string.split()]
stems[:10]

['accord', 'to', 'linkedin', 'the', '1', 'most', 'promis', 'job', 'is', 'data']

In [32]:
# Join our lists of words into a string again; assign to a variable to save changes

article_stemmed = ' '.join(stems)
article_stemmed

'accord to linkedin the 1 most promis job is data scienc but we here at codeup understand chang career can be a daunt idea that where our free learn to code workshop come in on saturday 423 we will be teach a free learn to code workshop on the program languag python which is one of the major build block of data scienc what is data scienc what is python if your curiou join for free to learn the basic of python from our veri own instructor and get an introduct to the field of data scienc thi is all done from the comfort of home save your seat quickli our python workshop are alway in high demand what you need 1 laptop doe not matter what kind you need to be abl to access wifi and run an internet browser 2 to rsvp you can regist for the event below'

In [33]:
def stem (string):
    '''
     takes in a text and return the text after applying stemming to all the words.
    '''
    # Create porter stemmer.
    ps = nltk.porter.PorterStemmer()
    # Apply the stemmer to each word in our string.
    stems = [ps.stem(word) for word in string.split()]
    text_stemmed = ' '.join(stems)
    return text_stemmed

In [34]:
stem(string)

'accord to linkedin the 1 most promis job is data scienc but we here at codeup understand chang career can be a daunt idea that where our free learn to code workshop come in on saturday 423 we will be teach a free learn to code workshop on the program languag python which is one of the major build block of data scienc what is data scienc what is python if your curiou join for free to learn the basic of python from our veri own instructor and get an introduct to the field of data scienc thi is all done from the comfort of home save your seat quickli our python workshop are alway in high demand what you need 1 laptop doe not matter what kind you need to be abl to access wifi and run an internet browser 2 to rsvp you can regist for the event below'

In [38]:
def lemmatize (text):
    '''
     Takes in some text and return the text after applying lemmatization to each word.
    '''
    wnl = nltk.stem.WordNetLemmatizer()
    
    # Use the lemmatizer on each word in the list of words we created by using split.
    lemmas = [wnl.lemmatize(word) for word in text.split()]
    
    # Join our list of words into a string again; assign to a variable to save changes.
    text_lemmatized = ' '.join(lemmas)
    
    return text_lemmatized

In [39]:
lem_text =lemmatize(string)

In [40]:
lem_text

'according to linkedin the 1 most promising job is data science but we here at codeup understand changing career can be a daunting idea thats where our free learn to code workshop come in on saturday 423 we will be teaching a free learn to code workshop on the programming language python which is one of the major building block of data science what is data science what is python if youre curious join for free to learn the basic of python from our very own instructor and get an introduction to the field of data science this is all done from the comfort of home save your seat quickly our python workshop are always in high demand what you need 1 laptop doe not matter what kind you need to be able to access wifi and run an internet browser 2 to rsvp you can register for the event below'

In [41]:
def remove_stopwords (string, extra_words= [], exclude_words=[]):
    '''
    Takes in a strand return the text after removing all the stopwords.
    Parameters:
    string : text in  string type
    extra_words : list of additional stop words to include,
    exclude_words : list of any words that we don't want to remove.

    '''
    # standard English language stopwords list from nltk
    stopword_list = stopwords.words('english')
    
    #add extra_words
    stopword_list =stopword_list + extra_words
    
    #exclude words
    for element in exclude_words:
        if element in stopword_list:
            stopword_list.remove(element)
    # Split words.
    words = string.split()
    
    # Create a list of words from my string with stopwords removed and assign to variable.
    filtered_words = [word for word in words if word not in stopword_list]
    
    # Join words in the list back into strings; assign to a variable to keep changes.
    string_without_stopwords = ' '.join(filtered_words)
    
    return string_without_stopwords

In [42]:
stopword_list = stopwords.words('english')

In [43]:
stopword_list

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'no',
 'nor',
 'not',
 'only',
 'own',
 'same',
 'so',
 'than',
 'too',
 'very',
 's',
 't',
 'can',
 'will',
 'just',
 'don',
 "don't",
 'should',
 "should've",
 'now',
 'd',
 'll',
 'm',
 'o',
 're',
 've',
 'y',
 'ain',
 'aren',
 "aren't",
 'couldn',
 "couldn't",
 'didn',
 "didn't",
 'doesn',
 "doesn't",
 'hadn',
 "hadn't",
 'hasn',
 "hasn't",
 'haven',
 "haven't",
 'isn',
 "isn't",
 'ma',
 'mightn',
 "mightn't",
 'mustn',
 "mustn't",
 'needn',
 "needn't",
 'shan',
 "shan't",
 'shouldn',
 "shouldn't",
 'wasn',
 "wasn't",
 'weren',
 "weren't",
 'won',
 "won't",
 'wouldn',
 "wouldn't"]

In [44]:
#test my function
remove_stopwords(string)

'according linkedin 1 promising job data science codeup understand changing careers daunting idea thats free learn code workshops come saturday 423 teaching free learn code workshop programming language python one major building blocks data science data science python youre curious join free learn basics python instructors get introduction field data science done comfort home save seat quickly python workshops always high demand need 1 laptop matter kind need able access wifi run internet browser 2 rsvp register event'

In [45]:
news_df = a.get_news_articles(use_cache=True)

Getting business articles
Getting sports articles
Getting technology articles
Getting entertainment articles

In [46]:
news_df

,category,title,content,author,published
0,business,Rupee closes at all-time low of 77.50 against ...,The Indian rupee weakened further on Monday to...,Pragya Swastik,2022-05-09T15:27:43.000Z
1,business,India's biggest IPO of LIC subscribed nearly 3...,"LIC's IPO, India's biggest IPO which opened on...",Pragya Swastik,2022-05-09T14:10:38.000Z
2,business,Layout of 'world's first Bitcoin City' in El S...,El Salvador's President Nayib Bukele has share...,Hiral Goyal,2022-05-10T13:24:11.000Z
3,business,Musk's $44 bn Twitter deal at risk of being re...,Elon Musk's $44 billion offer to buy Twitter c...,Pragya Swastik,2022-05-10T09:16:16.000Z
4,business,Twitter will comply with EU content rules afte...,Tesla CEO Elon Musk has said that Twitter will...,Ridham Gambhir,2022-05-10T07:37:59.000Z
...,...,...,...,...,...
95,entertainment,"Ran out of money during lockdown, in theatre y...",Actress Sarika said that she ran out of money ...,Amartya Sharma,2022-05-10T12:41:52.000Z
96,entertainment,Sanjay told Big B 'I'm leaving because of Muku...,'Khuda Gawah' producer Manoj Desai said that S...,Ria Kapoor,2022-05-10T10:42:27.000Z
97,entertainment,Calling Marvel films 'lesser art' disrespectfu...,"Actress Elizabeth Olsen, who portrays Scarlet ...",Kriti Kambiri,2022-05-10T11:36:54.000Z
98,entertainment,Anupam hosts 'Fauda' actor Tsahi Halevi at his...,"Anupam Kher hosted Israeli actor Tsahi Halevi,...",Udit Gupta,2022-05-10T11:45:49.000Z
99,entertainment,There's no cut footage of Cruise in 'Doctor St...,'Doctor Strange in the Multiverse of Madness' ...,Amartya Sharma,2022-05-10T12:30:33.000Z

In [47]:
codeup_df = a.get_blog_articles(use_cache=True)

In [48]:
codeup_df

,title,published,content
0,Learn to Code: Python Workshop on 4/23,"Mar 31, 2022","According to LinkedIn, the “#1 Most Promising ..."
1,Coming Soon: Cloud Administration,"Mar 17, 2022",We’re launching a new program out of San Anton...
2,5 Books Every Woman In Tech Should Read,"Mar 8, 2022",On this International Women’s Day 2022 we want...
3,Codeup Start Dates for March 2022,"Jan 26, 2022",As we approach the end of January we wanted to...
4,VET TEC Funding Now Available For Dallas Veterans,"Jan 7, 2022",We are so happy to announce that VET TEC benef...
5,Dallas Campus Re-opens With New Grant Partner,"Dec 30, 2021",We are happy to announce that our Dallas campu...
6,Codeup’s Placement Team Continues Setting Records,"Nov 19, 2021",Our Placement Team is simply defined as a grou...
7,"IT Certifications 101: Why They Matter, and Wh...","Nov 18, 2021","AWS, Google, Azure, Red Hat, CompTIA…these are..."
8,A rise in cyber attacks means opportunities fo...,"Nov 17, 2021","In the last few months, the US has experienced..."
9,Use your GI Bill® benefits to Land a Job in Tech,"Nov 4, 2021","As the end of military service gets closer, ma..."
10,Which program is right for me: Cyber Security ...,"Oct 28, 2021",What IT Career should I choose?\nIf you’re thi...
11,What the Heck is System Engineering?,"Oct 21, 2021",Codeup offers a 13-week training program: Syst...
12,From Speech Pathology to Business Intelligence,"Oct 18, 2021","By: Alicia Gonzalez\nBefore Codeup, I was a ho..."
13,Boris – Behind the Billboards,"Oct 3, 2021",
14,Is Codeup the Best Bootcamp in San Antonio…or ...,"Sep 16, 2021",Looking for the best data science bootcamp in ...

In [49]:
def prepare_df (df, extra_words= ['rumors'], exclude_words=[]):
    '''
    takes in a df and
    '''
    #create a new df
    df2 = pd.DataFrame(columns = ['title','original'])
    df2['title'] = df['title']
    df2['original'] = df['content']
    #clean and tokenize
    for column in df2.columns:
        df2[column + '_clean']= [basic_clean(df2[column][string]) for string in range(0, len(df2))]
        df2[column + '_clean']=[tokenize(df2[column + '_clean'][string]) for string in range(0, len(df2))]
        #stemmed & lemmatize
        stem_list= []
        lemm_list= []
        stop_word = []
        for string in range(0, len(df2)):
            #remove stopwords
            stop_word.append(remove_stopwords(df2[column][string], extra_words= extra_words, exclude_words=exclude_words))
            #stemmed
            text_stem= stem(df2[column + '_clean'][string])
            stem_list.append(text_stem)
            #lemmatize
            text_lem = lemmatize(df2[column + '_clean'][string])
            lemm_list.append(text_lem)
        df2[column +'_stemmed'] = stem_list
        df2[column +'_lemmatize'] = lemm_list
        #df2[column + '_clean'] = stop_word
    
    return df2

In [50]:
df2 =prepare_df(codeup_df)

In [51]:
df2

,title,original,title_clean,title_stemmed,title_lemmatize,original_clean,original_stemmed,original_lemmatize
0,Learn to Code: Python Workshop on 4/23,"According to LinkedIn, the “#1 Most Promising ...",learn to code python workshop on 423,learn to code python workshop on 423,learn to code python workshop on 423,according to linkedin the 1 most promising job...,accord to linkedin the 1 most promis job is da...,according to linkedin the 1 most promising job...
1,Coming Soon: Cloud Administration,We’re launching a new program out of San Anton...,coming soon cloud administration,come soon cloud administr,coming soon cloud administration,were launching a new program out of san antoni...,were launch a new program out of san antonio w...,were launching a new program out of san antoni...
2,5 Books Every Woman In Tech Should Read,On this International Women’s Day 2022 we want...,5 books every woman in tech should read,5 book everi woman in tech should read,5 book every woman in tech should read,on this international womens day 2022 we wante...,on thi intern women day 2022 we want to tell s...,on this international woman day 2022 we wanted...
3,Codeup Start Dates for March 2022,As we approach the end of January we wanted to...,codeup start dates for march 2022,codeup start date for march 2022,codeup start date for march 2022,as we approach the end of january we wanted to...,as we approach the end of januari we want to l...,a we approach the end of january we wanted to ...
4,VET TEC Funding Now Available For Dallas Veterans,We are so happy to announce that VET TEC benef...,vet tec funding now available for dallas veterans,vet tec fund now avail for dalla veteran,vet tec funding now available for dallas veteran,we are so happy to announce that vet tec benef...,we are so happi to announc that vet tec benefi...,we are so happy to announce that vet tec benef...
5,Dallas Campus Re-opens With New Grant Partner,We are happy to announce that our Dallas campu...,dallas campus reopens with new grant partner,dalla campu reopen with new grant partner,dallas campus reopens with new grant partner,we are happy to announce that our dallas campu...,we are happi to announc that our dalla campu r...,we are happy to announce that our dallas campu...
6,Codeup’s Placement Team Continues Setting Records,Our Placement Team is simply defined as a grou...,codeups placement team continues setting records,codeup placement team continu set record,codeups placement team continues setting record,our placement team is simply defined as a grou...,our placement team is simpli defin as a group ...,our placement team is simply defined a a group...
7,"IT Certifications 101: Why They Matter, and Wh...","AWS, Google, Azure, Red Hat, CompTIA…these are...",it certifications 101 why they matter and why ...,it certif 101 whi they matter and whi they dont,it certification 101 why they matter and why t...,aws google azure red hat comptiathese are big ...,aw googl azur red hat comptiathes are big name...,aws google azure red hat comptiathese are big ...
8,A rise in cyber attacks means opportunities fo...,"In the last few months, the US has experienced...",a rise in cyber attacks means opportunities fo...,a rise in cyber attack mean opportun for veter...,a rise in cyber attack mean opportunity for ve...,in the last few months the us has experienced ...,in the last few month the us ha experienc doze...,in the last few month the u ha experienced doz...
9,Use your GI Bill® benefits to Land a Job in Tech,"As the end of military service gets closer, ma...",use your gi bill benefits to land a job in tech,use your gi bill benefit to land a job in tech,use your gi bill benefit to land a job in tech,as the end of military service gets closer man...,as the end of militari servic get closer mani ...,a the end of military service get closer many ...
10,Which program is right for me: Cyber Security ...,What IT Career should I choose?\nIf you’re thi...,which program is right for me cyber security o...,which program is right for me cyber secur or s...,which program is right for me cyber security o...,what it career should i choose\nif youre think...,what it career should i choos if your think ab...,what it career should i choose if youre thinki...
11,What the Heck is System Engineering?,Codeup offers a 13-week training program: Syst...,what the heck is system engineering,what the heck is system engin,what the heck is system engineering,codeup offers a 13week training program system...,codeup offer a 13week train program system eng...,codeup offer a 13week training program system ...
12,From Speech Pathology to Business Intelligence,"By: Alicia Gonzalez\nBefore Codeup, I was a ho...",from speech pathology to business intelligence,from speech patholog to busi intellig,from speech pathology to business intelligence,by alicia gonzalez\nbefore codeup i was a home...,by alicia gonzalez befor codeup i wa a home he...,by alicia gonzalez before codeup i wa a home h...
13,Boris – Behind the Billboards,,boris behind the billboards,bori behind the billboard,boris behind the billboard,,,
14,Is Codeup the Best Bootcamp in San Antonio…or ...,Looking for the best data science bootcamp in ...,is codeup the best bootcamp in san antonioor t...,is codeup the best bootcamp in san antonioor t...,is codeup the best bootcamp in san antonioor t...,looking for the best data science bootcamp in ...,look for the best data scienc bootcamp in the ...,looking for the best data science bootcamp in ...

In [52]:
df2.columns

Index(['title', 'original', 'title_clean', 'title_stemmed', 'title_lemmatize',
       'original_clean', 'original_stemmed', 'original_lemmatize'],
      dtype='object')

In [53]:
new_news = prepare_df(news_df)

In [54]:
new_news

,title,original,title_clean,title_stemmed,title_lemmatize,original_clean,original_stemmed,original_lemmatize
0,Rupee closes at all-time low of 77.50 against ...,The Indian rupee weakened further on Monday to...,rupee closes at alltime low of 7750 against us...,rupe close at alltim low of 7750 against us do...,rupee close at alltime low of 7750 against u d...,the indian rupee weakened further on monday to...,the indian rupe weaken further on monday to cl...,the indian rupee weakened further on monday to...
1,India's biggest IPO of LIC subscribed nearly 3...,"LIC's IPO, India's biggest IPO which opened on...",india ' s biggest ipo of lic subscribed nearly...,india ' s biggest ipo of lic subscrib nearli 3...,india ' s biggest ipo of lic subscribed nearly...,lic ' s ipo india ' s biggest ipo which opened...,lic ' s ipo india ' s biggest ipo which open o...,lic ' s ipo india ' s biggest ipo which opened...
2,Layout of 'world's first Bitcoin City' in El S...,El Salvador's President Nayib Bukele has share...,layout of ' world ' s first bitcoin city ' in ...,layout of ' world ' s first bitcoin citi ' in ...,layout of ' world ' s first bitcoin city ' in ...,el salvador ' s president nayib bukele has sha...,el salvador ' s presid nayib bukel ha share th...,el salvador ' s president nayib bukele ha shar...
3,Musk's $44 bn Twitter deal at risk of being re...,Elon Musk's $44 billion offer to buy Twitter c...,musk ' s 44 bn twitter deal at risk of being r...,musk ' s 44 bn twitter deal at risk of be repr...,musk ' s 44 bn twitter deal at risk of being r...,elon musk ' s 44 billion offer to buy twitter ...,elon musk ' s 44 billion offer to buy twitter ...,elon musk ' s 44 billion offer to buy twitter ...
4,Twitter will comply with EU content rules afte...,Tesla CEO Elon Musk has said that Twitter will...,twitter will comply with eu content rules afte...,twitter will compli with eu content rule after...,twitter will comply with eu content rule after...,tesla ceo elon musk has said that twitter will...,tesla ceo elon musk ha said that twitter will ...,tesla ceo elon musk ha said that twitter will ...
...,...,...,...,...,...,...,...,...
95,"Ran out of money during lockdown, in theatre y...",Actress Sarika said that she ran out of money ...,ran out of money during lockdown in theatre yo...,ran out of money dure lockdown in theatr you e...,ran out of money during lockdown in theatre yo...,actress sarika said that she ran out of money ...,actress sarika said that she ran out of money ...,actress sarika said that she ran out of money ...
96,Sanjay told Big B 'I'm leaving because of Muku...,'Khuda Gawah' producer Manoj Desai said that S...,sanjay told big b ' i ' m leaving because of m...,sanjay told big b ' i ' m leav becaus of mukul...,sanjay told big b ' i ' m leaving because of m...,' khuda gawah ' producer manoj desai said that...,' khuda gawah ' produc manoj desai said that s...,' khuda gawah ' producer manoj desai said that...
97,Calling Marvel films 'lesser art' disrespectfu...,"Actress Elizabeth Olsen, who portrays Scarlet ...",calling marvel films ' lesser art ' disrespect...,call marvel film ' lesser art ' disrespect to ...,calling marvel film ' lesser art ' disrespectf...,actress elizabeth olsen who portrays scarlet w...,actress elizabeth olsen who portray scarlet wi...,actress elizabeth olsen who portrays scarlet w...
98,Anupam hosts 'Fauda' actor Tsahi Halevi at his...,"Anupam Kher hosted Israeli actor Tsahi Halevi,...",anupam hosts ' fauda ' actor tsahi halevi at h...,anupam host ' fauda ' actor tsahi halevi at hi...,anupam host ' fauda ' actor tsahi halevi at hi...,anupam kher hosted israeli actor tsahi halevi ...,anupam kher host isra actor tsahi halevi who s...,anupam kher hosted israeli actor tsahi halevi ...
99,There's no cut footage of Cruise in 'Doctor St...,'Doctor Strange in the Multiverse of Madness' ...,there ' s no cut footage of cruise in ' doctor...,there ' s no cut footag of cruis in ' doctor s...,there ' s no cut footage of cruise in ' doctor...,' doctor strange in the multiverse of madness ...,' doctor strang in the multivers of mad ' scre...,' doctor strange in the multiverse of madness ...